apiVersion: apps/v1
kind: Deployment
metadata:
  name: haris-capstone-project
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: devops-capstone-container
        image: ntharish13/harish-capstone:latest
        ports:
        - containerPort: 80