apiVersion: apps/v1
kind: Deployment
metadata:
  name: harish-capstone
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harish-capstone
  template:
    metadata:
      labels:
        app: harish-capstone
    spec:
      containers:
      - name: harish-capstone
        image: ntharish13/harish-capstone:latest
        ports:
        - containerPort: 80
          name: default-port