apiVersion: v1
kind: Service
metadata:
  name: harish-capstone-project
  labels:
    name: capstone
spec:
  selector:
    app: capstone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer