apiVersion: v1
kind: Service
metadata:
  name: harish-capstone
  labels:
    name: harish-capstone
spec:
  selector:
    app: harish-capstone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer