apiVersion: v1
kind: Service
metadata:
  name: harish-capstone-project
  labels:
    name: web
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80
  type: LoadBalancer